### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BulSV** [ArTTo8/RS232Terminal#1]
**Исправить:**
- [x] 1. Не запоминает состояние после перезапуска:
- [x] 1.1. Port.
- [x] 1.2. Baud.
- [x] 1.3. Bytes count.
- [x] 1.4. Echo mode (checkbox & spinbox).
- [x] 1.5. Auto scrolling.
- [x] 1.6. Send (spinbox).
- [x] 1.7. Загруженные файлы макросов (названия на кнопках), т. е. всё пишет в главный файл настроек, даже если файлы для пакета существуют.
- [x] 1.8. Установленные в макросах checkbox'ы.
- [x] 2. При загрузке программы не активны checkbox'ы и кнопки отправки пакетов, когда в lineEdit'ах есть текст.
- [x] 3. В Echo mode длина пакетов по строке осталась не корректной.

**Ввести:**
- [x] 1. Видимость полосы прокрутки в макросах - всегда.
- [x] 2. В Echo mode сделать checkbox активным всегда.
- [x] 3. Добавить шрифт Lucida Console в ресурсы программы (на общих документах есть шрифт).
- [x] 4. Шрифт в lineEdit'ах макросов - Lucida Console.
- [x] 5. Фон в lineEdit'ах макросов - черный.
- [x] 6. Текст в lineEdit'ах макросов - зелёный.
- [x] 7. Выбор Data bits: 5, 6, 7, 8.
- [x] 8. Выбор Parity: None, Odd, Even, Mark, Space.
- [x] 9. Выбор Stop bits: 1, 1.5, 2.
- [x] 10. Возможность ввода имени com-порта вручную (для Linux систем).
- [x] 11. Изменить базовый класс главного окна с QWidget на QMainWindow.
- [ ] 12. Переделать архитектуру программы в целом, используя паттерны проектирования.
- [x] 13. Кнопка загрузить файлы макросов (Load from files). Загрузка макросов из директории с помощью выделения нескольких файлов и последующим созданием виджетов для новых макросов. Старые макросы остаются, при этом, на своих местах, а новые добавляются вниз.
- [x] 14. В главном окне справа "выдвижной" (по нажатию кнопки - тонкая по горизонтали, по вертикали занимает всю область главного окна справа, с изменяющейся стрелкой: > - при спрятанном окне, < - при видимом окне) виджет управления отправкой макросов с кнопками отправки и checkbox'ами установки времени. Чтобы не открывать каждый раз диалог управления макросами. (См. Бланшет Ж., Саммерфилд М. Qt 4: программирование GUI на C++. Пер. с англ. 2-е изд., доп. - М.: КУДИЦ-ПРЕСС, 2008. - 736 с. , С.31-38 "Изменяющиеся диалоговые окна").
- [x] 15. Запоминать положение "выдвижного" виджета (виден или нет).
- [x] 16. В "выдвижном" виджете сделать checkbox - выделить всё (Check all), чтобы выбрать все checkbox'ы макросов.
- [x] 17. Раздельные режимы представления данных в read/write окнах: HEX, DEC, BIN, BIN-DEC, ASCII (для BIN-DEC и ASCII будет уточнено позднее).
- [x] 18. Раздельная установка максимального количества строчек в read/write окнах.
- [x] 19. Сохранение в текстовой файл раздельно содержимого read/write окон (в отличии от п.20 записываются строчки, доступные на данный момент, тогда как в п.20 создается отдельный буфер, в который записываются строчки пока не будет нажата кнопка Stop log).
- [x] 20. Добавить кнопки для каждого read/write окон Start log & Stop log для записи в файл с именем по умолчанию: YYYYMMDDHHMMSS.log (пример: 20160514212459.log); или под именем, указанным пользователем в диалоге сохранения. Ограничение по времени записи внести в файл настроек (чтобы можно было при необходимости его изменить) равным 10 минут.
- [x] 21. Выделение и копирование текста в read/write окнах.
- [x] 22. Если не помещается в read/write окнах пакет в строчку - сделать горизонтальную полосу прокрутки.
- [x] 23. Сделать возможность перетягивать перегородку между read/write окнами влево-вправо, увеличивая/уменьшая размеры окон по горизонтали.
- [ ] 24. Выборочная установка символа-разделителя (вместо $ по умолчанию).
- [ ] 25. Сделать отдельный поток для передачи/приема данных. Основной поток - для всего остального (интерфейса и т. д.).
- [x] 26. Сделать режим ASCII-кодов (помимо HEX-режима с $-разделителем), когда пакеты вводятся и отправляются без $-разделителя (будет уточнено позднее).
- [ ] 27. Сделать поддержку скриптов на Python'е: добавить выпадающий список (в Menu Bar'е QMainWindow) со всеми скриптами (элемент списка - имя файла скрипта без расширения), которые находятся в папке Scripts (интерфейс для внедрения скриптов будет уточнён позднее). Скорее всего будут создаваться пакеты и правлила их отправки.
