### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alxgord** [ArTTo8/RS232Terminal#3]
- [ ] Маска ввода
- [x] Возможность переключения между периодом и интервалом
- [x] PlainTextEdit заменить на ListView
- [ ] в ASCII режиме пофиксить single send le
